//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas_MVC.WCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaUsuario", Namespace="http://schemas.datacontract.org/2004/07/WCFVentas")]
    [System.SerializableAttribute()]
    public partial class RespuestaUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ventas", Namespace="http://schemas.datacontract.org/2004/07/WCFVentas")]
    [System.SerializableAttribute()]
    public partial class Ventas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaI {
            get {
                return this.FechaIField;
            }
            set {
                if ((this.FechaIField.Equals(value) != true)) {
                    this.FechaIField = value;
                    this.RaisePropertyChanged("FechaI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((this.ProductoField.Equals(value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendedor {
            get {
                return this.VendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendedorField, value) != true)) {
                    this.VendedorField = value;
                    this.RaisePropertyChanged("Vendedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detalles", Namespace="http://schemas.datacontract.org/2004/07/WCFVentas")]
    [System.SerializableAttribute()]
    public partial class Detalles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ventaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_venta {
            get {
                return this.Id_ventaField;
            }
            set {
                if ((this.Id_ventaField.Equals(value) != true)) {
                    this.Id_ventaField = value;
                    this.RaisePropertyChanged("Id_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendedor {
            get {
                return this.VendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendedorField, value) != true)) {
                    this.VendedorField = value;
                    this.RaisePropertyChanged("Vendedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuardaUser", Namespace="http://schemas.datacontract.org/2004/07/WCFVentas")]
    [System.SerializableAttribute()]
    public partial class GuardaUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_InsertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usuario_InsertaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Inserta {
            get {
                return this.Fecha_InsertaField;
            }
            set {
                if ((this.Fecha_InsertaField.Equals(value) != true)) {
                    this.Fecha_InsertaField = value;
                    this.RaisePropertyChanged("Fecha_Inserta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Usuario {
            get {
                return this.Nombre_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_UsuarioField, value) != true)) {
                    this.Nombre_UsuarioField = value;
                    this.RaisePropertyChanged("Nombre_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario_Inserta {
            get {
                return this.Usuario_InsertaField;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario_InsertaField, value) != true)) {
                    this.Usuario_InsertaField = value;
                    this.RaisePropertyChanged("Usuario_Inserta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditarUser", Namespace="http://schemas.datacontract.org/2004/07/WCFVentas")]
    [System.SerializableAttribute()]
    public partial class EditarUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usuario_actualizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usuario_insertaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_usuario {
            get {
                return this.Id_usuarioField;
            }
            set {
                if ((this.Id_usuarioField.Equals(value) != true)) {
                    this.Id_usuarioField = value;
                    this.RaisePropertyChanged("Id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_usuario {
            get {
                return this.Nombre_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_usuarioField, value) != true)) {
                    this.Nombre_usuarioField = value;
                    this.RaisePropertyChanged("Nombre_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario_actualiza {
            get {
                return this.Usuario_actualizaField;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario_actualizaField, value) != true)) {
                    this.Usuario_actualizaField = value;
                    this.RaisePropertyChanged("Usuario_actualiza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario_inserta {
            get {
                return this.Usuario_insertaField;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario_insertaField, value) != true)) {
                    this.Usuario_insertaField = value;
                    this.RaisePropertyChanged("Usuario_inserta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EliminarUser", Namespace="http://schemas.datacontract.org/2004/07/WCFVentas")]
    [System.SerializableAttribute()]
    public partial class EliminarUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_usuario {
            get {
                return this.Id_usuarioField;
            }
            set {
                if ((this.Id_usuarioField.Equals(value) != true)) {
                    this.Id_usuarioField = value;
                    this.RaisePropertyChanged("Id_usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InicioSesion", ReplyAction="http://tempuri.org/IService1/InicioSesionResponse")]
        Ventas_MVC.WCF.RespuestaUsuario InicioSesion(Ventas_MVC.WCF.RespuestaUsuario datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InicioSesion", ReplyAction="http://tempuri.org/IService1/InicioSesionResponse")]
        System.Threading.Tasks.Task<Ventas_MVC.WCF.RespuestaUsuario> InicioSesionAsync(Ventas_MVC.WCF.RespuestaUsuario datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarVentas", ReplyAction="http://tempuri.org/IService1/GuardarVentasResponse")]
        Ventas_MVC.WCF.Ventas GuardarVentas(Ventas_MVC.WCF.Ventas datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuardarVentas", ReplyAction="http://tempuri.org/IService1/GuardarVentasResponse")]
        System.Threading.Tasks.Task<Ventas_MVC.WCF.Ventas> GuardarVentasAsync(Ventas_MVC.WCF.Ventas datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerVenta", ReplyAction="http://tempuri.org/IService1/VerVentaResponse")]
        Ventas_MVC.WCF.Detalles VerVenta(Ventas_MVC.WCF.Detalles ver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerVenta", ReplyAction="http://tempuri.org/IService1/VerVentaResponse")]
        System.Threading.Tasks.Task<Ventas_MVC.WCF.Detalles> VerVentaAsync(Ventas_MVC.WCF.Detalles ver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/creausuario", ReplyAction="http://tempuri.org/IService1/creausuarioResponse")]
        Ventas_MVC.WCF.GuardaUser creausuario(Ventas_MVC.WCF.GuardaUser datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/creausuario", ReplyAction="http://tempuri.org/IService1/creausuarioResponse")]
        System.Threading.Tasks.Task<Ventas_MVC.WCF.GuardaUser> creausuarioAsync(Ventas_MVC.WCF.GuardaUser datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editar", ReplyAction="http://tempuri.org/IService1/editarResponse")]
        Ventas_MVC.WCF.EditarUser editar(Ventas_MVC.WCF.EditarUser datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editar", ReplyAction="http://tempuri.org/IService1/editarResponse")]
        System.Threading.Tasks.Task<Ventas_MVC.WCF.EditarUser> editarAsync(Ventas_MVC.WCF.EditarUser datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar", ReplyAction="http://tempuri.org/IService1/eliminarResponse")]
        Ventas_MVC.WCF.EliminarUser eliminar(Ventas_MVC.WCF.EliminarUser datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminar", ReplyAction="http://tempuri.org/IService1/eliminarResponse")]
        System.Threading.Tasks.Task<Ventas_MVC.WCF.EliminarUser> eliminarAsync(Ventas_MVC.WCF.EliminarUser datos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Ventas_MVC.WCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Ventas_MVC.WCF.IService1>, Ventas_MVC.WCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ventas_MVC.WCF.RespuestaUsuario InicioSesion(Ventas_MVC.WCF.RespuestaUsuario datos) {
            return base.Channel.InicioSesion(datos);
        }
        
        public System.Threading.Tasks.Task<Ventas_MVC.WCF.RespuestaUsuario> InicioSesionAsync(Ventas_MVC.WCF.RespuestaUsuario datos) {
            return base.Channel.InicioSesionAsync(datos);
        }
        
        public Ventas_MVC.WCF.Ventas GuardarVentas(Ventas_MVC.WCF.Ventas datos) {
            return base.Channel.GuardarVentas(datos);
        }
        
        public System.Threading.Tasks.Task<Ventas_MVC.WCF.Ventas> GuardarVentasAsync(Ventas_MVC.WCF.Ventas datos) {
            return base.Channel.GuardarVentasAsync(datos);
        }
        
        public Ventas_MVC.WCF.Detalles VerVenta(Ventas_MVC.WCF.Detalles ver) {
            return base.Channel.VerVenta(ver);
        }
        
        public System.Threading.Tasks.Task<Ventas_MVC.WCF.Detalles> VerVentaAsync(Ventas_MVC.WCF.Detalles ver) {
            return base.Channel.VerVentaAsync(ver);
        }
        
        public Ventas_MVC.WCF.GuardaUser creausuario(Ventas_MVC.WCF.GuardaUser datos) {
            return base.Channel.creausuario(datos);
        }
        
        public System.Threading.Tasks.Task<Ventas_MVC.WCF.GuardaUser> creausuarioAsync(Ventas_MVC.WCF.GuardaUser datos) {
            return base.Channel.creausuarioAsync(datos);
        }
        
        public Ventas_MVC.WCF.EditarUser editar(Ventas_MVC.WCF.EditarUser datos) {
            return base.Channel.editar(datos);
        }
        
        public System.Threading.Tasks.Task<Ventas_MVC.WCF.EditarUser> editarAsync(Ventas_MVC.WCF.EditarUser datos) {
            return base.Channel.editarAsync(datos);
        }
        
        public Ventas_MVC.WCF.EliminarUser eliminar(Ventas_MVC.WCF.EliminarUser datos) {
            return base.Channel.eliminar(datos);
        }
        
        public System.Threading.Tasks.Task<Ventas_MVC.WCF.EliminarUser> eliminarAsync(Ventas_MVC.WCF.EliminarUser datos) {
            return base.Channel.eliminarAsync(datos);
        }
    }
}
