#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas_MVC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ventas_progra2")]
	public partial class VentasBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCategorias(Categorias instance);
    partial void UpdateCategorias(Categorias instance);
    partial void DeleteCategorias(Categorias instance);
    partial void InsertProductos(Productos instance);
    partial void UpdateProductos(Productos instance);
    partial void DeleteProductos(Productos instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertVentas(Ventas instance);
    partial void UpdateVentas(Ventas instance);
    partial void DeleteVentas(Ventas instance);
    #endregion
		
		public VentasBDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Ventas_progra2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VentasBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentasBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentasBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VentasBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categorias> Categorias
		{
			get
			{
				return this.GetTable<Categorias>();
			}
		}
		
		public System.Data.Linq.Table<Productos> Productos
		{
			get
			{
				return this.GetTable<Productos>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Ventas> Ventas
		{
			get
			{
				return this.GetTable<Ventas>();
			}
		}
		
		public System.Data.Linq.Table<V_producto> V_producto
		{
			get
			{
				return this.GetTable<V_producto>();
			}
		}
		
		public System.Data.Linq.Table<V_venta> V_venta
		{
			get
			{
				return this.GetTable<V_venta>();
			}
		}
		
		public System.Data.Linq.Table<V_usuarios> V_usuarios
		{
			get
			{
				return this.GetTable<V_usuarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EditarCategoria")]
		public ISingleResult<SP_EditarCategoriaResult> SP_EditarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idcategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, descripcion, usuario, idcategoria);
			return ((ISingleResult<SP_EditarCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EditarProducto")]
		public ISingleResult<SP_EditarProductoResult> SP_EditarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idcategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(16,2)")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idproducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, idcategoria, precio, usuario, idproducto);
			return ((ISingleResult<SP_EditarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EditarVenta")]
		public ISingleResult<SP_EditarVentaResult> SP_EditarVenta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idproducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idventa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cantidad, idproducto, cliente, usuario, idventa);
			return ((ISingleResult<SP_EditarVentaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _Nombre_categoria;
		
		private string _Descripcion_categoria;
		
		private string _usuario_inserta;
		
		private System.Nullable<System.DateTime> _fecha_inserta;
		
		private string _usuario_actualiza;
		
		private System.Nullable<System.DateTime> _fecha_actualiza;
		
		private EntitySet<Productos> _Productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void OnNombre_categoriaChanging(string value);
    partial void OnNombre_categoriaChanged();
    partial void OnDescripcion_categoriaChanging(string value);
    partial void OnDescripcion_categoriaChanged();
    partial void Onusuario_insertaChanging(string value);
    partial void Onusuario_insertaChanged();
    partial void Onfecha_insertaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_insertaChanged();
    partial void Onusuario_actualizaChanging(string value);
    partial void Onusuario_actualizaChanged();
    partial void Onfecha_actualizaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_actualizaChanged();
    #endregion
		
		public Categorias()
		{
			this._Productos = new EntitySet<Productos>(new Action<Productos>(this.attach_Productos), new Action<Productos>(this.detach_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_categoria", DbType="VarChar(50)")]
		public string Nombre_categoria
		{
			get
			{
				return this._Nombre_categoria;
			}
			set
			{
				if ((this._Nombre_categoria != value))
				{
					this.OnNombre_categoriaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_categoria = value;
					this.SendPropertyChanged("Nombre_categoria");
					this.OnNombre_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion_categoria", DbType="VarChar(50)")]
		public string Descripcion_categoria
		{
			get
			{
				return this._Descripcion_categoria;
			}
			set
			{
				if ((this._Descripcion_categoria != value))
				{
					this.OnDescripcion_categoriaChanging(value);
					this.SendPropertyChanging();
					this._Descripcion_categoria = value;
					this.SendPropertyChanged("Descripcion_categoria");
					this.OnDescripcion_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_inserta", DbType="VarChar(50)")]
		public string usuario_inserta
		{
			get
			{
				return this._usuario_inserta;
			}
			set
			{
				if ((this._usuario_inserta != value))
				{
					this.Onusuario_insertaChanging(value);
					this.SendPropertyChanging();
					this._usuario_inserta = value;
					this.SendPropertyChanged("usuario_inserta");
					this.Onusuario_insertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inserta", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inserta
		{
			get
			{
				return this._fecha_inserta;
			}
			set
			{
				if ((this._fecha_inserta != value))
				{
					this.Onfecha_insertaChanging(value);
					this.SendPropertyChanging();
					this._fecha_inserta = value;
					this.SendPropertyChanged("fecha_inserta");
					this.Onfecha_insertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_actualiza", DbType="VarChar(50)")]
		public string usuario_actualiza
		{
			get
			{
				return this._usuario_actualiza;
			}
			set
			{
				if ((this._usuario_actualiza != value))
				{
					this.Onusuario_actualizaChanging(value);
					this.SendPropertyChanging();
					this._usuario_actualiza = value;
					this.SendPropertyChanged("usuario_actualiza");
					this.Onusuario_actualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_actualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_actualiza
		{
			get
			{
				return this._fecha_actualiza;
			}
			set
			{
				if ((this._fecha_actualiza != value))
				{
					this.Onfecha_actualizaChanging(value);
					this.SendPropertyChanging();
					this._fecha_actualiza = value;
					this.SendPropertyChanged("fecha_actualiza");
					this.Onfecha_actualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Productos", Storage="_Productos", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<Productos> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Productos(Productos entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = this;
		}
		
		private void detach_Productos(Productos entity)
		{
			this.SendPropertyChanging();
			entity.Categorias = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Productos")]
	public partial class Productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_producto;
		
		private string _Nombre_producto;
		
		private System.Nullable<int> _id_categoria;
		
		private System.Nullable<decimal> _precio;
		
		private string _usuario_inserta;
		
		private System.Nullable<System.DateTime> _fecha_inserta;
		
		private string _usuario_actualiza;
		
		private System.Nullable<System.DateTime> _fecha_actualiza;
		
		private EntitySet<Ventas> _Ventas;
		
		private EntityRef<Categorias> _Categorias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void OnNombre_productoChanging(string value);
    partial void OnNombre_productoChanged();
    partial void Onid_categoriaChanging(System.Nullable<int> value);
    partial void Onid_categoriaChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void Onusuario_insertaChanging(string value);
    partial void Onusuario_insertaChanged();
    partial void Onfecha_insertaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_insertaChanged();
    partial void Onusuario_actualizaChanging(string value);
    partial void Onusuario_actualizaChanged();
    partial void Onfecha_actualizaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_actualizaChanged();
    #endregion
		
		public Productos()
		{
			this._Ventas = new EntitySet<Ventas>(new Action<Ventas>(this.attach_Ventas), new Action<Ventas>(this.detach_Ventas));
			this._Categorias = default(EntityRef<Categorias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_producto", DbType="VarChar(30)")]
		public string Nombre_producto
		{
			get
			{
				return this._Nombre_producto;
			}
			set
			{
				if ((this._Nombre_producto != value))
				{
					this.OnNombre_productoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_producto = value;
					this.SendPropertyChanged("Nombre_producto");
					this.OnNombre_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int")]
		public System.Nullable<int> id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._Categorias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_inserta", DbType="VarChar(50)")]
		public string usuario_inserta
		{
			get
			{
				return this._usuario_inserta;
			}
			set
			{
				if ((this._usuario_inserta != value))
				{
					this.Onusuario_insertaChanging(value);
					this.SendPropertyChanging();
					this._usuario_inserta = value;
					this.SendPropertyChanged("usuario_inserta");
					this.Onusuario_insertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inserta", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inserta
		{
			get
			{
				return this._fecha_inserta;
			}
			set
			{
				if ((this._fecha_inserta != value))
				{
					this.Onfecha_insertaChanging(value);
					this.SendPropertyChanging();
					this._fecha_inserta = value;
					this.SendPropertyChanged("fecha_inserta");
					this.Onfecha_insertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_actualiza", DbType="VarChar(50)")]
		public string usuario_actualiza
		{
			get
			{
				return this._usuario_actualiza;
			}
			set
			{
				if ((this._usuario_actualiza != value))
				{
					this.Onusuario_actualizaChanging(value);
					this.SendPropertyChanging();
					this._usuario_actualiza = value;
					this.SendPropertyChanged("usuario_actualiza");
					this.Onusuario_actualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_actualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_actualiza
		{
			get
			{
				return this._fecha_actualiza;
			}
			set
			{
				if ((this._fecha_actualiza != value))
				{
					this.Onfecha_actualizaChanging(value);
					this.SendPropertyChanging();
					this._fecha_actualiza = value;
					this.SendPropertyChanged("fecha_actualiza");
					this.Onfecha_actualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Productos_Ventas", Storage="_Ventas", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<Ventas> Ventas
		{
			get
			{
				return this._Ventas;
			}
			set
			{
				this._Ventas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorias_Productos", Storage="_Categorias", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public Categorias Categorias
		{
			get
			{
				return this._Categorias.Entity;
			}
			set
			{
				Categorias previousValue = this._Categorias.Entity;
				if (((previousValue != value) 
							|| (this._Categorias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categorias.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Categorias.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("Categorias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ventas(Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Productos = this;
		}
		
		private void detach_Ventas(Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Productos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _Usuario;
		
		private string _Contraseña;
		
		private string _usuario_inserta;
		
		private System.Nullable<System.DateTime> _fecha_inserta;
		
		private string _usuario_actualiza;
		
		private System.Nullable<System.DateTime> _fecha_actualiza;
		
		private string _Nombre_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void Onusuario_insertaChanging(string value);
    partial void Onusuario_insertaChanged();
    partial void Onfecha_insertaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_insertaChanged();
    partial void Onusuario_actualizaChanging(string value);
    partial void Onusuario_actualizaChanged();
    partial void Onfecha_actualizaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_actualizaChanged();
    partial void OnNombre_usuarioChanging(string value);
    partial void OnNombre_usuarioChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(20)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_inserta", DbType="VarChar(50)")]
		public string usuario_inserta
		{
			get
			{
				return this._usuario_inserta;
			}
			set
			{
				if ((this._usuario_inserta != value))
				{
					this.Onusuario_insertaChanging(value);
					this.SendPropertyChanging();
					this._usuario_inserta = value;
					this.SendPropertyChanged("usuario_inserta");
					this.Onusuario_insertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inserta", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inserta
		{
			get
			{
				return this._fecha_inserta;
			}
			set
			{
				if ((this._fecha_inserta != value))
				{
					this.Onfecha_insertaChanging(value);
					this.SendPropertyChanging();
					this._fecha_inserta = value;
					this.SendPropertyChanged("fecha_inserta");
					this.Onfecha_insertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_actualiza", DbType="VarChar(50)")]
		public string usuario_actualiza
		{
			get
			{
				return this._usuario_actualiza;
			}
			set
			{
				if ((this._usuario_actualiza != value))
				{
					this.Onusuario_actualizaChanging(value);
					this.SendPropertyChanging();
					this._usuario_actualiza = value;
					this.SendPropertyChanged("usuario_actualiza");
					this.Onusuario_actualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_actualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_actualiza
		{
			get
			{
				return this._fecha_actualiza;
			}
			set
			{
				if ((this._fecha_actualiza != value))
				{
					this.Onfecha_actualizaChanging(value);
					this.SendPropertyChanging();
					this._fecha_actualiza = value;
					this.SendPropertyChanged("fecha_actualiza");
					this.Onfecha_actualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_usuario", DbType="VarChar(50)")]
		public string Nombre_usuario
		{
			get
			{
				return this._Nombre_usuario;
			}
			set
			{
				if ((this._Nombre_usuario != value))
				{
					this.OnNombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Nombre_usuario = value;
					this.SendPropertyChanged("Nombre_usuario");
					this.OnNombre_usuarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ventas")]
	public partial class Ventas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venta;
		
		private System.Nullable<int> _id_producto;
		
		private System.Nullable<System.DateTime> _Fecha_venta;
		
		private string _Usuario_venta;
		
		private System.Nullable<int> _Cantidad;
		
		private string _usuario_inserta;
		
		private System.Nullable<System.DateTime> _fecha_inserta;
		
		private string _usuario_actualiza;
		
		private System.Nullable<System.DateTime> _fecha_actualiza;
		
		private EntityRef<Productos> _Productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ventaChanging(int value);
    partial void Onid_ventaChanged();
    partial void Onid_productoChanging(System.Nullable<int> value);
    partial void Onid_productoChanged();
    partial void OnFecha_ventaChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_ventaChanged();
    partial void OnUsuario_ventaChanging(string value);
    partial void OnUsuario_ventaChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void Onusuario_insertaChanging(string value);
    partial void Onusuario_insertaChanged();
    partial void Onfecha_insertaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_insertaChanged();
    partial void Onusuario_actualizaChanging(string value);
    partial void Onusuario_actualizaChanged();
    partial void Onfecha_actualizaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_actualizaChanged();
    #endregion
		
		public Ventas()
		{
			this._Productos = default(EntityRef<Productos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_venta
		{
			get
			{
				return this._id_venta;
			}
			set
			{
				if ((this._id_venta != value))
				{
					this.Onid_ventaChanging(value);
					this.SendPropertyChanging();
					this._id_venta = value;
					this.SendPropertyChanged("id_venta");
					this.Onid_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int")]
		public System.Nullable<int> id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._Productos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_venta", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_venta
		{
			get
			{
				return this._Fecha_venta;
			}
			set
			{
				if ((this._Fecha_venta != value))
				{
					this.OnFecha_ventaChanging(value);
					this.SendPropertyChanging();
					this._Fecha_venta = value;
					this.SendPropertyChanged("Fecha_venta");
					this.OnFecha_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_venta", DbType="VarChar(50)")]
		public string Usuario_venta
		{
			get
			{
				return this._Usuario_venta;
			}
			set
			{
				if ((this._Usuario_venta != value))
				{
					this.OnUsuario_ventaChanging(value);
					this.SendPropertyChanging();
					this._Usuario_venta = value;
					this.SendPropertyChanged("Usuario_venta");
					this.OnUsuario_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_inserta", DbType="VarChar(50)")]
		public string usuario_inserta
		{
			get
			{
				return this._usuario_inserta;
			}
			set
			{
				if ((this._usuario_inserta != value))
				{
					this.Onusuario_insertaChanging(value);
					this.SendPropertyChanging();
					this._usuario_inserta = value;
					this.SendPropertyChanged("usuario_inserta");
					this.Onusuario_insertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inserta", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inserta
		{
			get
			{
				return this._fecha_inserta;
			}
			set
			{
				if ((this._fecha_inserta != value))
				{
					this.Onfecha_insertaChanging(value);
					this.SendPropertyChanging();
					this._fecha_inserta = value;
					this.SendPropertyChanged("fecha_inserta");
					this.Onfecha_insertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_actualiza", DbType="VarChar(50)")]
		public string usuario_actualiza
		{
			get
			{
				return this._usuario_actualiza;
			}
			set
			{
				if ((this._usuario_actualiza != value))
				{
					this.Onusuario_actualizaChanging(value);
					this.SendPropertyChanging();
					this._usuario_actualiza = value;
					this.SendPropertyChanged("usuario_actualiza");
					this.Onusuario_actualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_actualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_actualiza
		{
			get
			{
				return this._fecha_actualiza;
			}
			set
			{
				if ((this._fecha_actualiza != value))
				{
					this.Onfecha_actualizaChanging(value);
					this.SendPropertyChanging();
					this._fecha_actualiza = value;
					this.SendPropertyChanged("fecha_actualiza");
					this.Onfecha_actualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Productos_Ventas", Storage="_Productos", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public Productos Productos
		{
			get
			{
				return this._Productos.Entity;
			}
			set
			{
				Productos previousValue = this._Productos.Entity;
				if (((previousValue != value) 
							|| (this._Productos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Productos.Entity = null;
						previousValue.Ventas.Remove(this);
					}
					this._Productos.Entity = value;
					if ((value != null))
					{
						value.Ventas.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Productos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_producto")]
	public partial class V_producto
	{
		
		private int _id_producto;
		
		private string _Nombre_producto;
		
		private string _Nombre_categoria;
		
		private System.Nullable<decimal> _precio;
		
		private string _UltimoUsuarioActualiza;
		
		private System.Nullable<System.DateTime> _UltimaFechaActualiza;
		
		public V_producto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this._id_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_producto", DbType="VarChar(30)")]
		public string Nombre_producto
		{
			get
			{
				return this._Nombre_producto;
			}
			set
			{
				if ((this._Nombre_producto != value))
				{
					this._Nombre_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_categoria", DbType="VarChar(50)")]
		public string Nombre_categoria
		{
			get
			{
				return this._Nombre_categoria;
			}
			set
			{
				if ((this._Nombre_categoria != value))
				{
					this._Nombre_categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimoUsuarioActualiza", DbType="VarChar(50)")]
		public string UltimoUsuarioActualiza
		{
			get
			{
				return this._UltimoUsuarioActualiza;
			}
			set
			{
				if ((this._UltimoUsuarioActualiza != value))
				{
					this._UltimoUsuarioActualiza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimaFechaActualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> UltimaFechaActualiza
		{
			get
			{
				return this._UltimaFechaActualiza;
			}
			set
			{
				if ((this._UltimaFechaActualiza != value))
				{
					this._UltimaFechaActualiza = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_venta")]
	public partial class V_venta
	{
		
		private int _id_venta;
		
		private string _Nombre_producto;
		
		private System.Nullable<System.DateTime> _Fecha_venta;
		
		private string _Usuario_venta;
		
		private System.Nullable<int> _Cantidad;
		
		private string _usuario_inserta;
		
		private System.Nullable<System.DateTime> _fecha_inserta;
		
		private string _usuario_actualiza;
		
		private System.Nullable<System.DateTime> _fecha_actualiza;
		
		public V_venta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venta", DbType="Int NOT NULL")]
		public int id_venta
		{
			get
			{
				return this._id_venta;
			}
			set
			{
				if ((this._id_venta != value))
				{
					this._id_venta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_producto", DbType="VarChar(30)")]
		public string Nombre_producto
		{
			get
			{
				return this._Nombre_producto;
			}
			set
			{
				if ((this._Nombre_producto != value))
				{
					this._Nombre_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_venta", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_venta
		{
			get
			{
				return this._Fecha_venta;
			}
			set
			{
				if ((this._Fecha_venta != value))
				{
					this._Fecha_venta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_venta", DbType="VarChar(50)")]
		public string Usuario_venta
		{
			get
			{
				return this._Usuario_venta;
			}
			set
			{
				if ((this._Usuario_venta != value))
				{
					this._Usuario_venta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_inserta", DbType="VarChar(50)")]
		public string usuario_inserta
		{
			get
			{
				return this._usuario_inserta;
			}
			set
			{
				if ((this._usuario_inserta != value))
				{
					this._usuario_inserta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inserta", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inserta
		{
			get
			{
				return this._fecha_inserta;
			}
			set
			{
				if ((this._fecha_inserta != value))
				{
					this._fecha_inserta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_actualiza", DbType="VarChar(50)")]
		public string usuario_actualiza
		{
			get
			{
				return this._usuario_actualiza;
			}
			set
			{
				if ((this._usuario_actualiza != value))
				{
					this._usuario_actualiza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_actualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_actualiza
		{
			get
			{
				return this._fecha_actualiza;
			}
			set
			{
				if ((this._fecha_actualiza != value))
				{
					this._fecha_actualiza = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_usuarios")]
	public partial class V_usuarios
	{
		
		private int _id_usuario;
		
		private string _Usuario;
		
		private string _Contraseña;
		
		private string _usuario_inserta;
		
		private string _Nombre_usuario;
		
		private string _usuario_actualiza;
		
		private System.Nullable<System.DateTime> _fecha_actualiza;
		
		public V_usuarios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this._id_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(20)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_inserta", DbType="VarChar(50)")]
		public string usuario_inserta
		{
			get
			{
				return this._usuario_inserta;
			}
			set
			{
				if ((this._usuario_inserta != value))
				{
					this._usuario_inserta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_usuario", DbType="VarChar(50)")]
		public string Nombre_usuario
		{
			get
			{
				return this._Nombre_usuario;
			}
			set
			{
				if ((this._Nombre_usuario != value))
				{
					this._Nombre_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_actualiza", DbType="VarChar(50)")]
		public string usuario_actualiza
		{
			get
			{
				return this._usuario_actualiza;
			}
			set
			{
				if ((this._usuario_actualiza != value))
				{
					this._usuario_actualiza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_actualiza", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_actualiza
		{
			get
			{
				return this._fecha_actualiza;
			}
			set
			{
				if ((this._fecha_actualiza != value))
				{
					this._fecha_actualiza = value;
				}
			}
		}
	}
	
	public partial class SP_EditarCategoriaResult
	{
		
		private string _Error;
		
		public SP_EditarCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="NVarChar(4000)")]
		public string Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this._Error = value;
				}
			}
		}
	}
	
	public partial class SP_EditarProductoResult
	{
		
		private string _Error;
		
		public SP_EditarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="NVarChar(4000)")]
		public string Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this._Error = value;
				}
			}
		}
	}
	
	public partial class SP_EditarVentaResult
	{
		
		private string _Error;
		
		public SP_EditarVentaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="NVarChar(4000)")]
		public string Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this._Error = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
